name: Golden Cross Multi-Pair Check

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install requests pandas
      - run: python bot.py once
        env:
          OANDA_API_KEY: ${{ 0d83072b69a0909db195d7dfc1cafb00-903b5da342475fd76ada634d66e1ae71 }}
          OANDA_ACCOUNT_ID: ${{ 101-001-35932862-001 }}
